name: pripy3
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - networkx
  - matplotlib
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - eco
  - cvxpy
